" Setup a testing environment that is isolated from the other plugins.
"
filetype off

set runtimepath=vendor/vader.vim
set runtimepath+=.

filetype plugin on
filetype indent on

syntax enable

let mapleader = ";"
